"""Tests for the Protocol Experience generation helpers.

These target the pure heuristic paths (no OpenAI key, no vector DB) so they run
fast and deterministically. They ensure the experience degrades gracefully when
no LLM is configured and stays single-language.
"""

import asyncio
import re

import pytest

from app.experience_engine import (
    SEED_FRAGMENTS_EN,
    SEED_FRAGMENTS_JA,
    _heuristic_fragments,
    _heuristic_meaning,
    generate_fragments,
    generate_meaning,
    get_seed_fragments,
)
from app.fluke_engine import _heuristic_generate, generate_tension_and_prompt
from app.lenses import DEFAULT_LENS, available_lenses, get_lens
from app.models import Fragment


CJK = re.compile(r"[\u3040-\u30ff\u4e00-\u9fff]")
ASCII_LETTERS = re.compile(r"[A-Za-z]")

# Known English fallback templates that must never appear in Japanese output.
FORBIDDEN_EN_SNIPPETS = [
    "The encounter between",
    "reveals a boundary",
    "What new form of understanding",
    "at the intersection of these two fragments",
    "modes of understanding",
    "The meaning is still forming",
]


def _has_cjk(text: str) -> bool:
    return bool(CJK.search(text))


def _frag(text: str, fid: str) -> Fragment:
    return Fragment(id=fid, text=text, source="test", timestamp="2026-01-01T00:00:00Z", tags=[])


@pytest.fixture(autouse=True)
def _no_openai(monkeypatch):
    """Force heuristic fallback by removing any configured API key."""
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)


# --- Fragments ---


def test_heuristic_fragments_count_and_types_en():
    text = "I keep remembering a street in my old city. I have not decided whether to go back."
    frags = _heuristic_fragments(text, "en", get_lens("open"))
    assert 4 <= len(frags) <= 7
    types = {f.type for f in frags}
    assert types.issubset({"explicit", "inferred", "theme"})
    assert any(f.type == "explicit" for f in frags)
    assert any(f.type == "theme" for f in frags)
    assert all(f.text.strip() for f in frags)


def test_heuristic_fragments_japanese_is_japanese_only():
    text = "いま、あなたの中に残っているもの。まだ決められない選択がある。"
    frags = _heuristic_fragments(text, "ja", get_lens("open"))
    assert 4 <= len(frags) <= 7
    # Inferred and theme fragments are generated by us and must be Japanese.
    for f in frags:
        if f.type in ("inferred", "theme"):
            assert _has_cjk(f.text), f"Non-Japanese generated fragment: {f.text!r}"


def test_generated_fragments_are_concise():
    text = "最近、仕事を辞めようか迷っている。自由になりたいのに、その先が怖い。"
    frags = _heuristic_fragments(text, "ja", get_lens("open"))
    # Concise: no verbose explanatory sentences.
    for f in frags:
        assert len(f.text) <= 48


def test_generate_fragments_falls_back_without_key():
    frags = asyncio.run(generate_fragments("A question without an answer.", "en", "open"))
    assert 4 <= len(frags) <= 7


# --- Tension / reflection prompt ---


def test_tension_japanese_has_no_english_templates():
    a = _frag("手放せない記憶", "a1")
    b = _frag("まだ下していない選択", "b1")
    tension, prompt = asyncio.run(generate_tension_and_prompt(a, b, None, "ja"))
    assert _has_cjk(tension)
    assert _has_cjk(prompt)
    for snippet in FORBIDDEN_EN_SNIPPETS:
        assert snippet not in tension
        assert snippet not in prompt


def test_tension_heuristic_japanese_direct():
    a = _frag("帰れない場所", "a2")
    b = _frag("終わっていない時間", "b2")
    tension, prompt = _heuristic_generate(a, b, "ja")
    assert _has_cjk(tension) and _has_cjk(prompt)
    # No forbidden abstract/technical terms in Japanese tension.
    for term in ["boundary", "mode", "intersection", "resonance"]:
        assert term not in tension.lower()


def test_tension_english_stays_english():
    a = _frag("a memory you can't release", "a3")
    b = _frag("the path not taken", "b3")
    tension, prompt = asyncio.run(generate_tension_and_prompt(a, b, None, "en"))
    assert ASCII_LETTERS.search(tension)
    assert not _has_cjk(tension)


# --- Meaning ---


def test_meaning_japanese_is_japanese():
    meaning = _heuristic_meaning(
        "決められないと思っていたけれど、まだ終わらせていなかった。", "緊張", "ja", get_lens("open")
    )
    assert _has_cjk(meaning)
    assert "The meaning is still forming" not in meaning


def test_meaning_japanese_empty_reflection_stays_japanese():
    meaning = _heuristic_meaning("", "", "ja", get_lens("open"))
    assert _has_cjk(meaning)


def test_meaning_english_echoes_reflection():
    meaning = asyncio.run(
        generate_meaning(
            source_text="source",
            original_text="a",
            sampled_text="b",
            tension="t",
            reflection="Freedom requires a new rhythm.",
            language="en",
            lens_id="open",
        )
    )
    assert "rhythm" in meaning.lower()
    assert not _has_cjk(meaning)


def test_meaning_is_concise():
    meaning = _heuristic_meaning(
        "とても長い省察がここに続きます。しかし最後の一文は短い。", "t", "ja", get_lens("open")
    )
    assert len(meaning) <= 60


# --- Seed corpus / lenses ---


def test_seed_corpus_language_separation():
    assert len(SEED_FRAGMENTS_EN) >= 8
    assert len(SEED_FRAGMENTS_JA) >= 8
    assert all(_has_cjk(s["text"]) for s in SEED_FRAGMENTS_JA)
    assert all(not _has_cjk(s["text"]) for s in SEED_FRAGMENTS_EN)
    assert get_seed_fragments("ja") is SEED_FRAGMENTS_JA
    assert get_seed_fragments("en") is SEED_FRAGMENTS_EN


def test_lens_defaults_and_availability():
    assert get_lens(None).id == DEFAULT_LENS
    assert get_lens("nonexistent").id == DEFAULT_LENS
    assert any(lens.id == "open" for lens in available_lenses())
